# Generated by Django 4.2.7 on 2025-10-24 17:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(help_text="Nome do banco", max_length=100)),
                (
                    "codigo_banco",
                    models.CharField(
                        help_text="Código do banco (ex: 001, 237)", max_length=10
                    ),
                ),
                (
                    "agencia",
                    models.CharField(help_text="Número da agência", max_length=10),
                ),
                (
                    "conta",
                    models.CharField(
                        help_text="Número da conta com dígito", max_length=20
                    ),
                ),
                (
                    "tipo_conta",
                    models.CharField(
                        choices=[
                            ("CORRENTE", "Conta Corrente"),
                            ("POUPANCA", "Conta Poupança"),
                        ],
                        default="CORRENTE",
                        max_length=20,
                    ),
                ),
                (
                    "titular",
                    models.CharField(
                        help_text="Nome do titular da conta", max_length=200
                    ),
                ),
                (
                    "cpf_titular",
                    models.CharField(help_text="CPF do titular", max_length=14),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Bancária",
                "verbose_name_plural": "Contas Bancárias",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("SOLICITANTE", "Solicitante"),
                            ("APROVADOR", "Aprovador"),
                        ],
                        default="SOLICITANTE",
                        max_length=15,
                    ),
                ),
                ("cpf", models.CharField(blank=True, max_length=14, null=True)),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuários",
            },
        ),
        migrations.CreateModel(
            name="TravelRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destino", models.CharField(max_length=200, verbose_name="Destino")),
                ("data_viagem", models.DateField(verbose_name="Data da Viagem")),
                (
                    "quilometragem",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quilometragem rodada (km)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "valor_litro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor do litro da gasolina (R$)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "valor_total_combustivel",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total gasto com combustível (R$)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "nota_fiscal",
                    models.FileField(
                        help_text="Upload da nota fiscal de combustível",
                        upload_to="notas_fiscais/%Y/%m/",
                        verbose_name="Nota Fiscal",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADA", "Aprovada"),
                            ("REJEITADA", "Rejeitada"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Aprovação/Rejeição"
                    ),
                ),
                (
                    "observacoes_aprovador",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações do Aprovador"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "aprovador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_travels",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovador",
                    ),
                ),
                (
                    "conta_bancaria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="travels.bankaccount",
                        verbose_name="Conta para Reembolso",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Viagem",
                "verbose_name_plural": "Solicitações de Viagem",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
