# Generated by Django 4.2.7 on 2025-10-29 17:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        default="Sistema de Controle de Viagens",
                        max_length=100,
                        verbose_name="Nome da Aplicação",
                    ),
                ),
                (
                    "app_url",
                    models.URLField(
                        blank=True,
                        help_text="URL da aplicação (ex: http://192.168.1.100:8000)",
                        null=True,
                        verbose_name="URL da Aplicação",
                    ),
                ),
                (
                    "consumo_medio_padrao",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Consumo médio padrão dos veículos (km/L)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Consumo Médio Padrão",
                    ),
                ),
                (
                    "empresa",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome da Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do Sistema",
                "verbose_name_plural": "Configurações do Sistema",
            },
        ),
        migrations.AddField(
            model_name="travelrequest",
            name="consumo_medio",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Consumo médio do veículo (km/L)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="travelrequest",
            name="valor_litro",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.50"),
                help_text="Valor do litro da gasolina (R$)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="travelrequest",
            name="valor_total_combustivel",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                help_text="Valor total gasto com combustível (R$) - calculado automaticamente",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
