# Generated by Django 5.2.17 on 2026-09-12 01:48

import travels.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_systemconfig_travelrequest_consumo_medio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='nota_fiscal',
            field=models.FileField(help_text='PDF, JPG OU PNG , até 5MB', upload_to='notas_fiscais/%Y/%m/', validators=[travels.uploads.validar_nota_fiscal], verbose_name='Nota Fiscal'),
        ),
    ]
