# Generated by Django 5.2.17 on 2026-09-13 11:43

import travels.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_alter_travelrequest_nota_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='nota_fiscal',
            field=models.FileField(help_text='PDF, JPG OU PNG , até 5MB', upload_to=travels.uploads.caminho_nota_fiscal, validators=[travels.uploads.validar_nota_fiscal], verbose_name='Nota Fiscal'),
        ),
    ]
